## Get data

In [ ]:
import pickle
import pandas as pd
from scipy.stats import kendalltau, spearmanr
import numpy as np

with open('tournaments.pkl', 'rb') as f:
    df_tour = pickle.load(f)
with open('players.pkl', 'rb') as f:
    df_players = pickle.load(f)
with open('results.pkl', 'rb') as f:
    df_results = pickle.load(f)

In [ ]:
tournaments_df = pd.DataFrame.from_dict(df_tour, 'index')
players_df = pd.DataFrame.from_dict(df_players, 'index')
results_df = pd.DataFrame.from_dict(df_results, 'index')

In [ ]:
tournaments_df.head()

,id,name,dateStart,dateEnd,type,season,orgcommittee,synchData,questionQty
1,1,Чемпионат Южного Кавказа,2003-07-25T00:00:00+04:00,2003-07-27T00:00:00+04:00,"{'id': 2, 'name': 'Обычный'}",/seasons/1,[],None,None
2,2,Летние зори,2003-08-09T00:00:00+04:00,2003-08-09T00:00:00+04:00,"{'id': 2, 'name': 'Обычный'}",/seasons/1,[],None,None
3,3,Турнир в Ижевске,2003-11-22T00:00:00+03:00,2003-11-24T00:00:00+03:00,"{'id': 2, 'name': 'Обычный'}",/seasons/2,[],None,None
4,4,Чемпионат Украины. Переходной этап,2003-10-11T00:00:00+04:00,2003-10-12T00:00:00+04:00,"{'id': 2, 'name': 'Обычный'}",/seasons/2,[],None,None
5,5,Бостонское чаепитие,2003-10-10T00:00:00+04:00,2003-10-13T00:00:00+04:00,"{'id': 2, 'name': 'Обычный'}",/seasons/2,[],None,None

In [ ]:
tournaments_df.shape

(5528, 9)

In [ ]:
players_df.head()

    id     name  patronymic    surname
1    1  Алексей        None   Абабилов
10  10    Игорь                 Абалов
11  11  Наталья     Юрьевна  Абалымова
12  12    Артур  Евгеньевич    Абальян
13  13     Эрик  Евгеньевич    Абальян

In [ ]:
players_df.shape

(204063, 4)

In [ ]:
results_df.head()

,0,1,2,3,4,5,6,7,8,9,...,2054,2055,2056,2057,2058,2059,2060,2061,2062,2063
1,"{'team': {'id': 242, 'name': 'Команда Азимова'...","{'team': {'id': 640, 'name': 'Перезагрузка', '...","{'team': {'id': 245, 'name': 'Айастан', 'town'...","{'team': {'id': 299, 'name': 'Команда Гусейнов...","{'team': {'id': 1189, 'name': 'Грааль', 'town'...","{'team': {'id': 251, 'name': 'Пентиум', 'town'...","{'team': {'id': 268, 'name': 'Команда Алиева',...","{'team': {'id': 307, 'name': 'Третий путь', 't...","{'team': {'id': 543, 'name': 'Команда Мусаева'...","{'team': {'id': 41, 'name': 'Фантазия', 'town'...",...,None,None,None,None,None,None,None,None,None,None
2,"{'team': {'id': 312, 'name': 'Социал-демократы...","{'team': {'id': 510, 'name': 'Импульс', 'town'...","{'team': {'id': 195, 'name': 'Реал-Мордовия', ...","{'team': {'id': 264, 'name': 'Джокер', 'town':...","{'team': {'id': 240, 'name': 'Бегемот', 'town'...","{'team': {'id': 689, 'name': 'Б-52', 'town': {...","{'team': {'id': 258, 'name': 'МордоBOYS', 'tow...","{'team': {'id': 558, 'name': 'НТР', 'town': {'...","{'team': {'id': 285, 'name': 'Лис', 'town': {'...","{'team': {'id': 361, 'name': '1Ф', 'town': {'i...",...,None,None,None,None,None,None,None,None,None,None
3,"{'team': {'id': 175, 'name': 'Транссфера', 'to...","{'team': {'id': 5, 'name': 'Команда Кузьмина',...","{'team': {'id': 670, 'name': 'Ксеп', 'town': {...","{'team': {'id': 194, 'name': 'Десятый вал', 't...","{'team': {'id': 1, 'name': 'Неспроста', 'town'...","{'team': {'id': 14, 'name': 'СПС', 'town': {'i...","{'team': {'id': 188, 'name': 'Команда Губанова...","{'team': {'id': 173, 'name': 'ЮМА', 'town': {'...","{'team': {'id': 200, 'name': 'ОНУ им. Мечников...","{'team': {'id': 1733, 'name': 'Суббота 13', 't...",...,None,None,None,None,None,None,None,None,None,None
4,"{'team': {'id': 2205, 'name': 'ХИИТ - 2000', '...","{'team': {'id': 26956, 'name': 'Приматы', 'tow...","{'team': {'id': 26955, 'name': 'Сливки - Форс-...","{'team': {'id': 192, 'name': 'Гамбринус', 'tow...","{'team': {'id': 83, 'name': 'МПС', 'town': {'i...","{'team': {'id': 695, 'name': 'Легион', 'town':...","{'team': {'id': 552, 'name': 'Дуплет', 'town':...","{'team': {'id': 293, 'name': 'Чёрная кошка', '...","{'team': {'id': 493, 'name': 'Beit Grand - Або...","{'team': {'id': 267, 'name': 'Торпедный отсек'...",...,None,None,None,None,None,None,None,None,None,None
5,"{'team': {'id': 1733, 'name': 'Суббота 13', 't...","{'team': {'id': 108, 'name': 'Задумчивый жираф...","{'team': {'id': 425, 'name': 'Бостон-6', 'town...","{'team': {'id': 271, 'name': 'Саша и медведи',...","{'team': {'id': 494, 'name': 'Гигантские дятлы...","{'team': {'id': 2562, 'name': 'Мадагаскар', 't...","{'team': {'id': 100, 'name': 'Сигма', 'town': ...","{'team': {'id': 351, 'name': 'Снарки', 'town':...","{'team': {'id': 709, 'name': 'Легионеры', 'tow...","{'team': {'id': 647, 'name': 'Вашингтонские му...",...,None,None,None,None,None,None,None,None,None,None

In [ ]:
for el in df_results[1]:
    print(el)
    break

{'team': {'id': 242, 'name': 'Команда Азимова', 'town': {'id': 21, 'name': 'Баку'}}, 'mask': None, 'current': {'name': 'Команда Азимова', 'town': {'id': 21, 'name': 'Баку'}}, 'questionsTotal': 0, 'synchRequest': None, 'position': 1, 'controversials': [], 'flags': [], 'teamMembers': [{'flag': None, 'usedRating': 0, 'rating': 0, 'player': {'id': 476, 'name': 'Анар', 'patronymic': 'Беюкага оглы', 'surname': 'Азимов'}}, {'flag': None, 'usedRating': 0, 'rating': 0, 'player': {'id': 878, 'name': 'Фариз', 'patronymic': 'Наим оглы', 'surname': 'Аликишибеков'}}, {'flag': None, 'usedRating': 0, 'rating': 0, 'player': {'id': 1872, 'name': 'Аднан', 'patronymic': 'Фариз оглы', 'surname': 'Ахундов'}}, {'flag': None, 'usedRating': 0, 'rating': 0, 'player': {'id': 13721, 'name': 'Балаш', 'patronymic': 'Алекпер оглы', 'surname': 'Касумов'}}, {'flag': None, 'usedRating': 0, 'rating': 0, 'player': {'id': 22132, 'name': 'Анар', 'patronymic': 'Джафар оглы', 'surname': 'Наджафли'}}, {'flag': None, 'usedRating': 0, 'rating': 0, 'player': {'id': 22133, 'name': 'Рауф', 'patronymic': 'Джафар оглы', 'surname': 'Наджафли'}}]}

In [ ]:
def get_dataset(df_results, df_tour, year):
    answers = []
    members = []
    tournaments = []
    qty = []
    round_qty = []
    numbers_qt = []
    teams = []
    places = []
    quest_id = []
    for tournament_id in df_tour:
        if not df_tour[tournament_id]['dateStart'].split("-")[0] == year:
            continue
        for el in df_results[tournament_id]:
            rounds = []
            for key, value in df_tour[tournament_id]["questionQty"].items():
                rounds.extend([key] * value)
            answers_to_quest = el.get("mask", [])
            #print(rounds, answers_to_quest)
            num_of_questions = len(answers_to_quest) if answers_to_quest is not None else 0
            for member in [member["player"]["id"] for member in el["teamMembers"]]:
                for i in range(num_of_questions):
                    #print(round_num, i)
                    #print(answers_to_quest, num_of_questions, num_of_rounds, tournament_id)
                    if answers_to_quest[i] == '1' or answers_to_quest[i] == '0':
                      qty.append(df_tour[tournament_id]["questionQty"])
                      tournaments.append(tournament_id)
                      members.append(member)
                      teams.append(el['team']['id'])
                      quest_id.append(str(tournament_id)+'_'+str(i))
                      answers.append(int(answers_to_quest[i]))
                      numbers_qt.append(i + 1)
                      round_qty.append(int(rounds[min(i, len(rounds) - 1)]))
                      places.append(el['position'])
    dfs = pd.DataFrame({"answer": answers, "player_id": members, "tournament_id": tournaments, 'team_id': teams, 'position': places, 'question_id': quest_id})
    dfs = dfs[~dfs.answer.isna()]
    return dfs
#dfs.head()
train_dataset = get_dataset(df_results, df_tour, "2019")
test_dataset = get_dataset(df_results, df_tour, "2020")

In [ ]:
train_dataset.head(10)

   answer  player_id  tournament_id  team_id  position question_id
0       1       6212           4772    45556       1.0      4772_0
1       1       6212           4772    45556       1.0      4772_1
2       1       6212           4772    45556       1.0      4772_2
3       1       6212           4772    45556       1.0      4772_3
4       1       6212           4772    45556       1.0      4772_4
5       1       6212           4772    45556       1.0      4772_5
6       1       6212           4772    45556       1.0      4772_6
7       1       6212           4772    45556       1.0      4772_7
8       1       6212           4772    45556       1.0      4772_8
9       0       6212           4772    45556       1.0      4772_9

In [ ]:
PLAYERS_ID = train_dataset['player_id'].unique()
len(PLAYERS_ID)

59101

## Linear model

качестве baseline модели построим линейную регрессию, которая будет обучать рейтинг-лист игроков.
для каждого игрока есть запись с ответом на вопрос, и сложностью вопроса. Сделаем one-hot по id участика и id вопроса, таргет - бинарный ответ на вопрос
train - турниры до 2019 года, test - после

In [ ]:
train_dataset['player_id'] = train_dataset['player_id'].astype('category')
train_dataset['question_id'] = train_dataset['question_id'].astype('category')
X_train = pd.get_dummies(train_dataset[['player_id', 'question_id']], sparse = True)
y_train = train_dataset['answer']
X_train

,player_id_15,player_id_16,player_id_23,player_id_31,player_id_35,player_id_38,player_id_47,player_id_59,player_id_65,player_id_79,...,question_id_6255_90,question_id_6255_91,question_id_6255_92,question_id_6255_93,question_id_6255_94,question_id_6255_95,question_id_6255_96,question_id_6255_97,question_id_6255_98,question_id_6255_99
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20910735,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20910736,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20910737,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20910738,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20910739,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
def get_rating(model, data, dict_res):
  cols = data.columns
  coef_rating = model.coef_
  for i in range(59101):
      ids = int(cols[i].split('_')[-1])
      dict_res[ids] = coef_rating[i]

In [ ]:
COEF_MODEL_DICT = {}
get_rating(model, X_train, COEF_MODEL_DICT)

In [ ]:
COEF_MODEL_DICT

{15: 0.15870045019366397,
 16: 0.3338789708502684,
 23: 0.2340006276978102,
 31: 0.20081693321449243,
 35: 0.20128198272784517,
 38: 0.020336037577717465,
 47: 0.3642801367502267,
 59: 0.22454113536451317,
 65: 0.10244877497906409,
 79: 0.18997648692329477,
 80: 0.3737570510619419,
 82: 0.1450276480150273,
 98: 0.0310337444829324,
 112: 0.14012067587245314,
 113: 0.21110499711264477,
 117: 0.4056631337382848,
 119: 0.18288727381898973,
 133: 0.3522135959661115,
 136: 0.09872428447751923,
 144: 0.5002622279386983,
 150: 0.35700034315100826,
 153: 0.3305857071633556,
 157: 0.10208809675559458,
 160: 0.4164767253217613,
 176: 0.4313983333516945,
 178: 0.22665817671230973,
 182: 0.24780283005515813,
 196: 0.1890850257738687,
 223: 0.40726256118014714,
 230: 0.33767825073485314,
 232: 0.11873803226050529,
 233: 0.11217956548726508,
 236: 0.4505992480612395,
 261: 0.22245057801641333,
 263: 0.1868754702608122,
 278: 0.31690181395474487,
 286: -0.014093969588733561,
 315: 0.38299978446219884,
 322: 0.2805928167994756,
 323: 0.39486544269155716,
 328: 0.3849208489247672,
 330: 0.21808731146736038,
 345: 0.38334406801613147,
 354: 0.03786526932199375,
 376: 0.4217167339941421,
 377: 0.10714983464994648,
 379: 0.33976724937148556,
 385: 0.2649546071732737,
 397: 0.36445338191264803,
 398: 0.3412270676393237,
 409: 0.19042027754322471,
 415: 0.2724100306716298,
 418: 0.17283767812306103,
 419: 0.45350931951296414,
 437: -0.006812521124744817,
 441: 0.2566150360581344,
 445: 0.17810055582802084,
 447: 0.35404154060567794,
 450: -0.12330846964613822,
 453: 0.1289768681842036,
 457: 0.36915159601649783,
 474: 0.19299048115043532,
 475: 0.30996165581361185,
 486: 0.24103695871871528,
 487: 0.36399853558455664,
 489: 0.41287803871454715,
 490: 0.4782577311013307,
 503: 0.28980870182071106,
 505: 0.5748947932032066,
 509: -0.0300380339749705,
 531: 0.12038194571662587,
 535: 0.3279414727519325,
 537: 0.20982676412700696,
 571: 0.19462802311737512,
 576: 0.24605316367562882,
 591: 0.12134138704638804,
 599: 0.16091761057626777,
 602: 0.1376863730891177,
 616: 0.16350896255371164,
 619: 0.24286891647125908,
 623: 0.269023942473055,
 631: 0.3174473437635249,
 639: 0.3974090893268852,
 641: 0.3967566751548962,
 643: 0.44634139453851784,
 644: 0.354144377740802,
 656: 0.5105314249919666,
 658: 0.3819804618682088,
 660: 0.22049101257120154,
 662: 0.1818960143313159,
 668: 0.27067396142806927,
 670: 0.1643100202622588,
 680: 0.3099519475702139,
 683: 0.3817093008443189,
 691: 0.049200801312399775,
 696: 0.4579730408812344,
 699: 0.04730403928935753,
 707: 0.5894119383860854,
 712: 0.2550732076900728,
 716: 0.06423370039808105,
 726: 0.21311486623004064,
 730: 0.18053154809182187,
 731: 0.06786923968766155,
 740: 0.29738311683221086,
 747: 0.4558673250421709,
 757: 0.015687522481383383,
 772: 0.22167247604100115,
 777: 0.010076602835495083,
 781: 0.3257184422398898,
 789: 0.12135976729256608,
 797: 0.2987043100065859,
 798: 0.27176395585571234,
 803: 0.3897846327765161,
 808: 0.29983411632484946,
 811: 0.27737793583069764,
 822: 0.2885396717210899,
 824: 0.04390394603493853,
 837: 0.10606288751654269,
 840: 0.35020996236708185,
 849: 0.30802862480216486,
 851: -0.04807901289355088,
 853: 0.22276973318729318,
 856: 0.2750040360602879,
 860: 0.35311698086287946,
 868: 0.17417156939174755,
 869: -0.05611228138798948,
 881: 0.13161525860526022,
 885: 0.4243857067476429,
 887: 0.11094862829163583,
 902: 0.31762341210519124,
 904: 0.46852485598701454,
 907: -0.15555301453720607,
 929: 0.1663352734770475,
 932: 0.48323526866981564,
 935: -0.1323345854723419,
 950: 0.40191518184689595,
 958: 0.3411560433367743,
 960: 0.21312299129292359,
 992: 0.07433988617983844,
 1000: 0.44396072000481973,
 1001: 0.48848682152095657,
 1007: 0.17569357030069582,
 1019: 0.1977070181051355,
 1022: 0.30439618480821723,
 1029: 0.1597813674777995,
 1033: 0.3124032506245293,
 1042: 0.1802363102117908,
 1043: 0.4087129395395085,
 1049: 0.07506045369622628,
 1050: 0.38294166004635116,
 1055: 0.2898617740034714,
 1062: 0.4547647785173971,
 1068: 0.3205625434461639,
 1073: 0.016357239151951447,
 1076: 0.31278487371282887,
 1123: 0.2139739143828077,
 1136: 0.37095244390639837,
 1137: 0.3154045624704735,
 1140: 0.2768613799913393,
 1145: 0.3907345361822568,
 1157: 0.07639774180031682,
 1158: 0.22146591354667472,
 1169: 0.2273696945539669,
 1174: 0.28532465455449324,
 1192: 0.08139525039317312,
 1197: 0.29491120281061656,
 1215: 0.08696686081857448,
 1218: 0.1417587079556291,
 1239: -0.06703367697761084,
 1243: 0.17187244342218264,
 1246: 0.28191374508549727,
 1257: 0.17923214052465353,
 1261: 0.32506146010677,
 1265: 0.04092481910279422,
 1266: 0.1455457476731889,
 1284: 0.2908417857376691,
 1288: 0.11528952456878236,
 1302: 0.11528952456878236,
 1304: 0.16591046664022308,
 1305: 0.43390947423165993,
 1313: 0.22116016141047784,
 1325: 0.22528999900823263,
 1339: 0.3458666960950486,
 1340: 0.40234529588465817,
 1344: 0.4082794933238382,
 1345: 0.20674130136025398,
 1348: 0.336762975147256,
 1349: 0.1908391876244873,
 1350: 0.21857271714322013,
 1351: 0.13482790755171087,
 1352: 0.4766448301563511,
 1354: 0.42108077727491416,
 1364: 0.4427917584578655,
 1369: 0.39158160846619733,
 1370: 0.3917412272973977,
 1372: 0.2612852833910076,
 1375: 0.06146533761435604,
 1386: 0.06896616864116097,
 1387: 0.5202032767922323,
 1391: 0.08726091756774984,
 1406: 0.2423108923246018,
 1412: 0.22609754956616815,
 1424: 0.33933986391546633,
 1425: 0.2751506764915331,
 1432: 0.17462217448653694,
 1433: 0.11828555704587689,
 1444: 0.16879347066713077,
 1450: 0.3274995449783878,
 1454: 0.05011012785531817,
 1468: 0.4113817838939464,
 1471: 0.21527966072023172,
 1472: 0.11048670398665825,
 1477: 0.17003820112881152,
 1487: 0.184560108782372,
 1488: 0.19120875331643947,
 1498: 0.15422863201321713,
 1506: 0.2620506903132807,
 1511: 0.29700265777992,
 1513: 0.3903769725336301,
 1516: 0.14331867223803066,
 1517: 0.19110370237911864,
 1531: 0.17147330798384855,
 1540: 0.42070634912911353,
 1562: 0.4934260278097885,
 1579: 0.19462802311737512,
 1581: 0.17688205143390845,
 1584: 0.3712075405952917,
 1585: 0.5823215228116959,
 1590: 0.19665808445403765,
 1599: 0.4530795647621792,
 1603: 0.2769534923648728,
 1608: 0.19025576799466873,
 1615: -0.09698237734141034,
 1616: -0.09698237734141034,
 1619: -0.0627009555097595,
 1625: 0.3844907831917616,
 1632: -0.02824120971783539,
 1641: 0.24558035155148505,
 1646: 0.40791429653273525,
 1672: 0.15330242132273772,
 1681: 0.2986436374481834,
 1683: 0.3058142878593619,
 1701: 0.27696333627050984,
 1704: -0.06197579887543944,
 1706: 0.10465044801841515,
 1707: 0.14594466475529838,
 1732: 0.3812679560245958,
 1743: 0.22110269298428725,
 1746: 0.1393465619463245,
 1750: 0.2520473514248816,
 1752: 0.2999272889782284,
 1756: 0.32996011062721325,
 1791: 0.33954805443109504,
 1804: 0.20698586187016663,
 1807: 0.22597754611803167,
 1809: 0.19937226260581636,
 1826: 0.14001243574113048,
 1859: 0.057262666884359686,
 1867: 0.10231704743261669,
 1869: 0.12571019454605925,
 1871: 0.2925533073048121,
 1886: -0.06120316660004133,
 1894: 0.3170564891606494,
 1898: 0.2660332003604448,
 1899: 0.19644584567138412,
 1902: 0.4368957482806711,
 1906: 0.08572332111654096,
 1907: 0.4596105875977862,
 1919: 0.3399549373784462,
 1934: 0.2230605171497982,
 1940: 0.2715630126085836,
 1948: 0.3628448456915342,
 1960: 0.16459284920984124,
 1964: 0.2726049149929301,
 1966: 0.3811063077052771,
 1970: 0.3340391390935256,
 1981: 0.22630752663914783,
 1983: 0.24822899816397598,
 2001: 0.2576901632505722,
 2004: 0.3578363676139365,
 2005: 0.45691792001502823,
 2013: 0.07428977890121105,
 2027: 0.20922880958864287,
 2031: 0.37065303297719354,
 2033: 0.40373856497912947,
 2054: 0.383104467441309,
 2065: 0.3506232781499416,
 2066: 0.34655339449650163,
 2077: 0.2334891089873045,
 2094: 0.2545162822333987,
 2097: 0.25307375568330787,
 2103: 0.27851651345614964,
 2115: 0.3455542613516181,
 2116: 0.15271715088867757,
 2137: 0.1896826898271095,
 2150: 0.09477454683316802,
 2154: 0.12023407424711176,
 2155: 0.13986348076384575,
 2171: 0.30326016612359125,
 2174: 0.19688396239772107,
 2187: -0.020218657559702213,
 2194: 0.2919349236011172,
 2217: 0.3594361242189997,
 2220: 0.18170314370031745,
 2221: 0.39457851719542664,
 2223: 0.15786280730678764,
 2226: 0.3101153118025903,
 2229: 0.27467507910327954,
 2230: -0.01989744402226725,
 2231: -0.01989744402226725,
 2233: 0.24105375907200016,
 2251: 0.2448022769899655,
 2268: 0.2959453266953237,
 2282: 0.36670539910409267,
 2283: 0.17002258641084533,
 2284: 0.16776345971706919,
 2287: 0.40198333191359464,
 2291: 0.1002751717507987,
 2318: 0.3243672123043737,
 2319: 0.2523224036505649,
 2322: 0.502264673732818,
 2323: 0.25062628778933166,
 2336: 0.24706551909591085,
 2344: 0.1937427181954862,
 2382: 0.2313998442375559,
 2384: 0.47066114854516244,
 2391: 0.18333706685448484,
 2393: 0.21151876256426028,
 2396: 0.38762604102007114,
 2404: 0.19072866460283025,
 2414: 0.3725359576928431,
 2421: 0.5395079294725128,
 2424: 0.20801765022567273,
 2429: 0.25269971727751106,
 2441: 0.2305680896608357,
 2443: 0.1574228542139503,
 2448: 0.41311094270626403,
 2457: -0.01929047603801722,
 2463: 0.20501774692556488,
 2465: 0.08828424699476639,
 2466: 0.3328596695374628,
 2475: 0.4102864115962257,
 2490: 0.3653918305181089,
 2502: 0.4458133824052163,
 2514: 0.12474131572513329,
 2515: 0.12474131572513329,
 2529: 0.3611481819457045,
 2530: 0.3611481819457045,
 2541: 0.24605316367562882,
 2548: 0.4548386782414541,
 2569: 0.13317603254303104,
 2580: 0.39256375550959577,
 2594: 0.20960202425042798,
 2595: 0.3082937745944396,
 2600: 0.2633879937133081,
 2612: 0.4250055652137761,
 2623: 0.15551847766011836,
 2628: 0.09247638117218548,
 2642: 0.37689977134897146,
 2643: 0.3699239514327648,
 2659: 0.26844049596539327,
 2668: 0.3038399623109168,
 2673: 0.43931694685433315,
 2678: 0.3674266543436001,
 2694: 0.38838724066968583,
 2695: 0.11226479864836512,
 2697: -0.029870611549235062,
 2698: 0.42239178204236283,
 2705: 0.3445565188012792,
 2706: 0.3412693456466928,
 2712: 0.20783890083555154,
 2717: 0.08617380994060642,
 2719: 0.015836651176844085,
 2727: 0.068966168641161,
 2735: 0.3804956547807657,
 2742: 0.2811472836889317,
 2744: 0.2996698376713179,
 2758: 0.4939437261288969,
 2763: 0.3202042101144663,
 2766: 0.12978494396108112,
 2785: 0.35469936999850893,
 2791: 0.0809336837956196,
 2796: 0.20683171417744609,
 2797: 0.4566987632234734,
 2828: 0.40525921665367953,
 2829: 0.08616779874150844,
 2838: 0.19898765284264275,
 2851: 0.30805566346210966,
 2857: 0.4584407482779379,
 2859: 0.03356056710119307,
 2860: 0.3277502426266067,
 2861: -0.0452188104258672,
 2870: 0.23383447698533438,
 2872: 0.32022912348803667,
 2874: 0.1657453293197661,
 2885: 0.4157057096032235,
 2888: 0.2628503296151848,
 2890: 0.2704111754161099,
 2891: 0.39385131226297704,
 2898: 0.33829660487325897,
 2902: 0.231318037753334,
 2904: 0.22003899921823167,
 2906: 0.2380089500311475,
 2907: 0.07045441089718905,
 2910: 0.47116630266653076,
 2914: 0.42291363528722387,
 2917: 0.1414515083378148,
 2920: 0.24311412992670792,
 2924: 0.042915821505899364,
 2927: 0.17113140944528715,
 2936: 0.23776063405927805,
 2938: 0.37132355939653094,
 2952: 0.4378542283149484,
 2954: 0.5204770283963636,
 2965: 0.10893694247983657,
 2973: 0.3033185670552077,
 2978: 0.12249060678405788,
 2992: 0.3411679018602141,
 2993: 0.2568100017123138,
 2998: 0.5462350468359389,
 3011: 0.43147884161754985,
 3013: 0.016357239151951447,
 3017: 0.08562301693566102,
 3026: 0.2694105715531417,
 3032: 0.4160823148522028,
 3036: 0.16942488687145602,
 3041: 0.33911926732884967,
 3056: 0.49152373052744475,
 3058: 0.3885140125552887,
 3065: 0.32277012290615215,
 3066: 0.09509866874999771,
 3067: 0.3138768414950452,
 3078: 0.22049101257120154,
 3081: 0.5410646729188675,
 3083: 0.4641062602722929,
 3085: 0.21668147689336675,
 3088: 0.4730295493393892,
 3096: 0.3664144588381572,
 3103: 0.07895876301138559,
 3114: 0.07895876301138559,
 3127: 0.04487321831080715,
 3132: -0.2583632197538507,
 3154: -0.010952330872503425,
 3157: 0.2567669281851056,
 3159: 0.5302575191680988,
 3163: 0.1304210675580004,
 3178: 0.37835615082356544,
 3179: 0.040419704462567624,
 3187: 0.36579432563487957,
 3197: 0.2797643580833032,
 3199: 0.23981926934490802,
 3207: 0.5061734157818719,
 3208: 0.2948213087785638,
 3217: 0.2946086705618906,
 3222: 0.37808089196642053,
 3231: 0.22950342912500174,
 3232: 0.06896616864116106,
 3239: 0.36717106541236977,
 3240: 0.3957186040057822,
 3241: 0.31438785036356837,
 3242: 0.44263923963439733,
 3256: 0.10530921343585409,
 3262: 0.039445628710879026,
 3268: 0.17596940937895333,
 3276: 0.3441999470947971,
 3278: 0.4933882246406889,
 3293: 0.3912903057453488,
 3294: 0.2568700494708783,
 3298: 0.27594495076451236,
 3315: 0.11157278644597472,
 3325: 0.1988467284871183,
 3327: 0.38190835113999194,
 3335: 0.11306195858666096,
 3344: 0.26910787978509426,
 3346: 0.15786280730678764,
 3347: 0.3060324261802288,
 3348: -0.17908038484522976,
 3350: 0.3213108135474452,
 3355: 0.2952660140579312,
 3356: 0.2276423962936895,
 3357: 0.12063512503732543,
 3360: 0.153432341833943,
 3381: 0.1996494765174479,
 3385: 0.10570903153128056,
 3386: 0.2634488413520577,
 3387: 0.24047504256521077,
 3408: 0.06583901165319105,
 3410: 0.08424256814843584,
 3414: 0.24304397648957138,
 3415: 0.42265549371452776,
 3417: 0.2573623958863068,
 3419: 0.29787306464867086,
 3422: 0.22457768394552818,
 3423: 0.3981169495730974,
 3425: 0.3765683765834863,
 3427: 0.2609601279831276,
 3428: 0.398297609959802,
 3431: -0.01989744402226725,
 3434: 0.34827735799196335,
 3436: 0.18426001499445396,
 3438: 0.5416164848821121,
 3440: 0.32594677969743774,
 3450: 0.31824717603032804,
 3464: 0.37872273340279994,
 3466: 0.18074568008492095,
 3467: 0.13337768226064403,
 3474: 0.3878855317003301,
 3496: 0.23927709141246548,
 3498: 0.19027682069296517,
 3499: 0.10661735183780167,
 3507: 0.3438252658444784,
 3512: 0.3166294133746064,
 3515: 0.18594590213932555,
 3532: -0.10114394753120388,
 3568: 0.41258693392895884,
 3577: 0.48128731968989474,
 3596: 0.3364313557651623,
 3603: 0.33004700161151396,
 3608: 0.2823966637056593,
 3617: 0.3220556496028924,
 3619: 0.11325809001184646,
 3630: 0.16518927886285795,
 3645: 0.34639666934043184,
 3651: 0.19661746860915186,
 3658: 0.3244972424369032,
 3668: 0.19263489683034526,
 3671: 0.5605733788850178,
 3677: 0.455009881866171,
 3684: 0.3297662492918783,
 3696: 0.25930699126079365,
 3701: 0.19023964001604138,
 3712: 0.20595647169734185,
 3721: 0.2931811696388376,
 3726: 0.29265032522169754,
 3736: 0.07352009837701724,
 3739: 0.4023965279318522,
 3747: 0.13253860063681736,
 3748: 0.3069974731302352,
 3752: 0.06987933632880691,
 3762: 0.4817734509278232,
 3767: 0.4478793994342902,
 3781: 0.21687206131943848,
 3787: 0.3234340147274154,
 3800: 0.3690433432751982,
 3803: 0.2569177893931276,
 3812: 0.40639827675021645,
 3818: 0.1597666460605788,
 3822: 0.2104822962408576,
 3823: 0.3539643723870787,
 3843: 0.5506738088668038,
 3868: 0.2536720313570849,
 3882: 0.2017445711512865,
 3883: 0.24473771654650806,
 3909: 0.3704270038723981,
 3910: 0.3758130223176141,
 3912: 0.22212794871849922,
 3914: 0.3376930366408731,
 3925: 0.4581194908068562,
 3939: 0.13299746881339702,
 3945: 0.3089168918873051,
 3963: 0.2506751020959325,
 3972: 0.3069974731302352,
 3974: 0.42872364174045513,
 3983: 0.1837001549835183,
 3996: 0.2506751020959325,
 4006: 0.31748916754453305,
 4018: 0.08577069316430344,
 4020: 0.4866796175633986,
 4022: 0.26092490355236037,
 4024: 0.2618887030150518,
 4026: 0.12992433648667168,
 4028: 0.33054220822858904,
 4039: 0.3627394807469483,
 4046: 0.323252824509553,
 4053: 0.2986756033304385,
 4063: 0.5490841363365876,
 4064: 0.46283895871882064,
 4075: 0.2707922438663386,
 4085: 0.23217353697739865,
 4095: 0.2788650825863606,
 4096: 0.15376741591279233,
 4098: 0.09493161947938504,
 4113: 0.29828684547396395,
 4114: 0.40790380328493486,
 4121: 0.4935860183848721,
 4123: -0.044230684287158206,
 4147: 0.1230341934949099,
 4159: -0.020058653232228434,
 4167: 0.32144469981330914,
 4180: 0.13317603254303104,
 4181: 0.4045010029590088,
 4191: 0.31129806789715625,
 4193: 0.1816902406844009,
 4198: 0.30504981337162534,
 4200: 0.17237202532985738,
 4213: 0.11104393079877971,
 4220: 0.29580011072172424,
 4223: 0.4745239787888604,
 4224: 0.1118715916234389,
 4226: 0.5864467215689568,
 4237: 0.2111196714206986,
 4239: 0.05087301684984764,
 4241: 0.2791916237372101,
 4246: 0.44723314462398983,
 4255: 0.30252261895558363,
 4258: 0.44386928378624657,
 4261: 0.4623404844027812,
 4262: 0.11992070169468715,
 4265: 0.29689027032201765,
 4270: 0.6556789985895399,
 4271: 0.2628038580221129,
 4281: 0.23582043471198996,
 4289: 0.33538032577140864,
 4295: 0.19054999369368747,
 4297: 0.27721146668443747,
 4298: -0.2626679744661712,
 4303: 0.10514800669439718,
 4307: 0.4020762113994459,
 4309: 0.024773588658670468,
 4337: 0.2537969055427044,
 4348: 0.09964340599107012,
 4349: 0.272191940223783,
 4382: 0.3184069505476466,
 4383: 0.335108726660822,
 4387: 0.20975921841282746,
 4394: 0.21312299129292359,
 4404: 0.25765363158686044,
 4408: 0.358991731382738,
 4414: 0.4328801123062513,
 4415: 0.19247748959602795,
 4417: 0.29795168552143575,
 4418: 0.14468560745006387,
 4426: 0.34847736922138195,
 4440: 0.3755853011163182,
 4442: 0.16358186749829096,
 4448: 0.29452117705868625,
 4456: 0.09937335555161003,
 4458: 0.41313735316215355,
 4477: 0.28894736724604175,
 4513: 0.2892596944367442,
 4515: 0.33407110535393447,
 4521: 0.06255174323731198,
 4536: 0.21324868038861677,
 4545: 0.09642211955619469,
 4551: 0.19752896055908695,
 4559: 0.08145101458140343,
 4579: 0.25559249615618795,
 4582: 0.3422286578391029,
 4586: 0.2885480736917297,
 4593: 0.2849645244717665,
 4599: 0.115124565117566,
 4602: 0.39902023980688767,
 4614: 0.4236911233385762,
 4616: 0.2969453172242465,
 4622: 0.23502987076197468,
 4623: 0.23399231062063458,
 4627: 0.28213381522995523,
 4637: 0.5325666545706599,
 4647: 0.20783890083555157,
 4650: 0.21351839296040814,
 4660: 0.17894318995648995,
 4668: 0.08431434579950245,
 4673: 0.2442322447546657,
 4677: 0.2907612446501501,
 4715: 0.36969681847009545,
 4722: 0.29682804256229356,
 4728: 0.32204790427085755,
 4730: 0.5107158457894039,
 4732: 0.27321757066765384,
 4733: 0.20971830362745222,
 4736: 0.34689337001407944,
 4742: 0.4358157057145764,
 4743: 0.3298611425447655,
 4753: 0.01052840855640277,
 4762: 0.30095665375184444,
 4763: 0.46423956786518294,
 4778: 0.44928407626445316,
 4786: 0.2192868692875647,
 4799: 0.1263345072002264,
 4802: 0.38338595574817996,
 4812: 0.13982013900730197,
 4813: 0.13941022115757049,
 4821: -0.0627009555097595,
 4847: 0.18185512236747625,
 4852: 0.4510918816937965,
 4854: 0.3768485467439583,
 4856: 0.2392930199398357,
 4861: 0.40573694550650524,
 4863: 0.32978696335990354,
 4864: 0.1912186337799481,
 4865: 0.08793353429822703,
 4869: 0.06229506193823849,
 4870: 0.41448439557394384,
 4872: 0.28388165418696093,
 4875: 0.5117674608140003,
 4876: 0.52089836901119,
 4878: 0.5388085015148834,
 4879: 0.35466367641864666,
 4886: 0.24252474547519653,
 4890: 0.37172665896700585,
 4894: 0.4154838114004651,
 4905: 0.1470426000332774,
 4906: 0.2100359355622254,
 4926: 0.25784512973348794,
 4940: 0.04090537478080756,
 4960: 0.39568926539082655,
 4964: 0.16310517136835714,
 4969: 0.07637507125345477,
 4973: 0.3973239224704083,
 4991: 0.22370288113345904,
 5004: 0.37266753836695304,
 5007: 0.48933983533776476,
 5018: 0.29164399778887773,
 5020: 0.15786280730678764,
 5023: 0.14799673780935782,
 5034: 0.2889718070446143,
 5043: 0.17810823201141923,
 5056: 0.45533951693275576,
 5076: -0.18322282596976425,
 5104: 0.4908389116708791,
 5124: 0.3663593383182332,
 5128: 0.2712738270371324,
 5130: 0.412432034942276,
 5140: 0.2007957587198894,
 5146: 0.35073199348478473,
 5150: 0.03900904311514734,
 5162: 0.4280787100014428,
 5181: 0.3138297231740552,
 5185: 0.2534011736706056,

рейтинг игрока - полученный в результате обучения коэффициент из линейной модели

# Tournir rating list

известны составы команд из теста, неизвестны вопросы. 

берем рейтинг игроков из модели и суммируем по команде, сортируем рейтинг таблицу по рассчитаному значению

в качестве метрики качества на тестовом наборе  ранговые корреляции Спирмена и Кендалла (бейзлайновые значения Спирмена на тестовом множестве порядка 0.7-0.8, Кендалла — 0.5-0.6)

In [ ]:
test_dataset.head()

   answer  player_id  tournament_id  team_id  position question_id
0       1      30152           4957    49804       1.0      4957_0
1       1      30152           4957    49804       1.0      4957_1
2       1      30152           4957    49804       1.0      4957_2
3       1      30152           4957    49804       1.0      4957_3
4       1      30152           4957    49804       1.0      4957_4

In [ ]:
tournaments = test_dataset.tournament_id.unique()

In [ ]:
all_t_spearmanr = []
all_t_kendalltau = []

for tournament in tqdm(tournaments):
    teams = test_dataset[test_dataset.tournament_id == tournament].team_id.unique()
    predicted = []
    true = []
    for team in teams:
        players = test_dataset[(test_dataset.tournament_id == tournament)&(test_dataset.team_id == team)].player_id.unique()
        result_sum = 0
        for player in players: 
            if player in COEF_MODEL_DICT.keys():
              result_sum += COEF_MODEL_DICT[player] 
        predicted.append(result_sum)
        true.append(test_dataset[(test_dataset['tournament_id'] == tournament)&(test_dataset['team_id'] == team)]['position'].iloc[0])
    predicted.reverse()
    all_t_spearmanr.append(spearmanr(predicted, true)[0])
    all_t_kendalltau.append(kendalltau(predicted, true)[0])

print('корреляция Спирмена:', np.mean(np.array(all_t_spearmanr)))
print('корреляция Кендалла:', np.mean(np.array(all_t_kendalltau)))

100%|██████████| 173/173 [13:21<00:00,  4.64s/it]

корреляция Спирмена: 0.7717972673887041
корреляция Кендалла: 0.6118052474501707

полученные ранговые корреляций в диапазоне безлайна, модель работает неплохо